### ISSUE TITLE
fix(build): typecheck:test red on main from the Kokoro cache-key spec

### ISSUE THREAD

**Issue by jcosta33** [jcosta33/sourdaw#2452]
### Subsystem

ai / airuntime (AI agentic tools, proposals, streaming)

### Priority

P2

### Defect

pnpm typecheck:test (tsc --noEmit -p tsconfig.test.json) fails on origin/main with two errors in src/modules/BrowserAi/useCases/__tests__/renderKokoroTts.spec.ts, introduced by #2380's cache-key test: TS2493 at line 243 (Tuple type '[]' of length '0' has no element at index '0') and TS2339 at line 245 (Property 'inputData' does not exist on type 'never'). The vi.mock for computeRenderCacheKey declares no parameters, so mock.calls[0]?.[0] types as never even though the test reads .inputData off it. Hosted checks do not run (health-gates is manual dispatch), so nothing caught it at merge, and every affected-only typecheck:test run for any later test-file change now reports these errors alongside its own. Expected: typecheck:test green on main — type the mock's call signature from the real computeRenderCachePoints input rather than reading fields off a never.

### Reproduce

1. Check out origin/main. 2. Run pnpm typecheck:test. 3. Observe the two errors above and exit 1. Verified on head 248449d94 with the #2437 lane's checks and confirmed pre-existing by stashing the lane's own changes and re-running.

### References

Introduced by #2380; surfaced while running the affected checks for PR #2451 (issue #2437).

**Comment by jcosta33** [comment]
Merged as d74d13d31 (PR #2459); GitHub cross-referenced the PR but did not auto-close from its body, so closing by hand per the issue-state exception.
